config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  
  root to: "home#index"

  get 'home/index'
  get 'dashboard/index'

  resources :articles, :except => [:index] do
    resource :vote, module: :articles, only: [:create, :destroy]
  end

  resources :categories

  devise_for :users, controllers: {
    sessions: 'users/sessions',
    passwords: 'users/passwords',
    registrations: 'users/registrations'
  }
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  resources :users, only: %i[show]
end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
  def index
    authorize! :manage, :dashboard
    @articles_num = Article.count
    @likes = Vote.count
    @categories_num = Category.count
    @articles_released = Article.released_with_attachements
    @latest_added_article = Article.heros.first
    @most_voted_article = Vote.most_voted_article
    @latest_added_category = Category.last
  end
end

app/helpers/dashboard_helper.rb
module DashboardHelper
  def latest_added_article_dashboard(article)
    if article.present?
      link_to("#{article.title}...", article_path(article))
    else
      link_to('No article added yet!', root_path)
    end
  end

  def most_voted_article_dashboard(article)
    if article.present?
      link_to("#{article.title}...", article_path(article))
    else
      link_to('No article voted yet!', root_path)
    end
  end

  def latest_added_category_dashboard(category)
    if category.present?
      link_to(category.name.to_s, category_path(category))
    else
      link_to('No category added yet!', root_path)
    end
  end
end

app/views/dashboard/_card.html.erb
<div class="dashbord_displayer_article_card">
    <div class="card_image">
        <%= image_tag(article.hero_image) %>
    </div>
    <div class="card_tools">
          <%= link_to 'Edit', edit_article_path(article), class: 'tool_box_link' %>
          <%= link_to 'Destroy', article, method: :delete, data: { confirm: 'Are you sure?' }, class: 'tool_box_link' %>
    </div>
    <div class="card_info">
        <p class="card_info_title category_last_article_hero_title">
            <%= link_to article_path(article) do %>
              <%= article.title %>
            <% end %>
        </p>
        <p class="card_info_text category_last_article_hero_content">
          <%= truncate(article.text, :omission => "...", :length => 250) %>
        </p>

        <table class= "card_info_table">
          <tr>
            <td class= "card_table_title">Votes:</td>
            <td>
                <span><%= article.votes_count %></span>
                <svg width="0.9em" height="0.9em" viewBox="0 0 16 16" class="bi bi-heart-fill" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
                  <path fill-rule="evenodd" d="M8 1.314C12.438-3.248 23.534 4.735 8 15-7.534 4.736 3.562-3.248 8 1.314z"/>
                </svg>
            </td>
          </tr>
          <tr>
            <td class= "card_table_title">Author:</td>
            <td>
                  <%= link_to user_path(article.author), class: 'readmore' do %>
                    <%= article.author.name%>
                  <% end %>
            </td>
          </tr>
          <tr>
            <td class= "card_table_title">Category:</td>
            <td>
                  <%= link_to category_path(article.category), class: 'readmore' do %>
                    <%= article.category.name%>
                  <% end %>
            </td>
          </tr>
        </table>
    </div>
</div>

app/views/dashboard/index.html.erb
<% provide(:title, 'Dashboard')%>

<section class="dashboard">
  <div class="dashboard_navigator">

      <div class="dashbord_header">
        <p>Hello, <%= current_user.name %>!</p>
        <p>Here is your Dashboard!</p>
      </div>

      <div class="dashboard_tool_box">
        <%= link_to 'Add new Category', new_category_path , class: 'tool_box_link' %>
        <%= link_to 'Add new Article', new_article_path, class: 'tool_box_link' %>
      </div>
      <div class="dashboard_tool_box">
        <%= link_to 'List of Categories', categories_path, class: 'tool_box_link' %>
        <%= link_to 'Edit Categories', new_category_path, class: 'tool_box_link' %>
      </div>

      <div class="dashboard_tool_box">
        <div class="dashboard_stats_header">
          Statistics:
        </div>
         <p class="dashboard_stats_data"><span><%= @articles_num %></span> Articles created</p>
         <p class="dashboard_stats_data"><span><%= @likes %></span> Likes</p>
         <p class="dashboard_stats_data"><span><%= @categories_num %></span> Categories</p>
      </div>

  </div>

  <div class="dashboard_displayer">

    <div class="dashboard_displayer_heros">

      <table class="dashboard_displayer_heros_table">
        <tr>
          <td class="dashboard_displayer_heros_type">The Latest Added Article: </td>
          <td class="dashboard_displayer_heros_link">
              <%= latest_added_article_dashboard(@latest_added_article) %>
          </td>
        </tr>
        <tr>
          <td class="dashboard_displayer_heros_type">The Most Voted Article: </td>
          <td class="dashboard_displayer_heros_link">
              <%= most_voted_article_dashboard(@most_voted_article) %>
          </td>
        </tr>

        <tr>
          <td class="dashboard_displayer_heros_type">The Latest Added Category: </td>
          <td class="dashboard_displayer_heros_link">
              <%= latest_added_category_dashboard(@latest_added_category) %>
          </td>
        </tr>
      </table>

    </div>

    <div class="dashbord_displayer_collection">
        <div class="dashbord_displayer_collection_header">
              <p>Articles to review:</p>
        </div>

        <div class="dashbord_displayer_collection_articles">
              <% if @articles_released.empty? %>
                    <p class="readmore">No articles added yet!</p>
              <% else %>
                    <%= render partial: 'dashboard/card', collection: @articles_released, as: :article, cached: true %>
              <% end %>
        </div>
    </div>

  </div>
</section>