config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  
  root to: "home#index"

  get 'home/index'
  get 'dashboard/index'

  resources :articles, :except => [:index] do
    resource :vote, module: :articles, only: [:create, :destroy]
  end

  resources :categories

  devise_for :users, controllers: {
    sessions: 'users/sessions',
    passwords: 'users/passwords',
    registrations: 'users/registrations'
  }
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  resources :users, only: %i[show]
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :articles

  validates :name, presence: true, uniqueness: { case_sensitive: false }
  validates :name, length: {
    minimum: 2,
    maximum: 20
  }
  validates :priority, presence: true, numericality: { only_integer: true, greater_than: 0 }

  scope :priority_sorted, -> { order(priority: :asc) }

  scope :importants, -> { priority_sorted.limit(4) }
  scope :important_with_articles, -> { importants.includes(articles: [image_attachment: :blob]) }

  def latest_article
    articles.heros.first
  end

  def articles_count
    articles.count
  end

  def votes_count
    count = 0
    articles.each do |art|
      count += art.votes_count
    end
    count
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :set_category, only: %i[show edit update destroy]
  skip_before_action :authenticate_user!, only: %i[show index]
  authorize_resource

  # GET /categories
  # GET /categories.json
  def index
    @categories = Category.paginate(page: params[:page], per_page: 6)
  end

  # GET /categories/1
  # GET /categories/1.json
  def show
    @articles = @category.articles.with_attached_image.paginate(page: params[:page], per_page: 4)
  end

  # GET /categories/new
  def new
    @category = Category.new
    @categories = Category.all
  end

  # GET /categories/1/edit
  def edit
    @categories = Category.all
  end

  # POST /categories
  # POST /categories.json
  def create
    @category = Category.new(category_params)

    respond_to do |format|
      if @category.save
        format.html { redirect_to new_category_url, notice: 'Category was successfully created.' }
      else
        flash[:error] = @category.errors.full_messages.to_sentence
        format.html { render :new }
      end
    end
  end

  # PATCH/PUT /categories/1
  # PATCH/PUT /categories/1.json
  def update
    respond_to do |format|
      if @category.update(category_params)
        format.html { redirect_to new_category_url, notice: 'Category was successfully updated.' }
      else
        flash[:error] = @category.errors.full_messages.to_sentence
        format.html { render :edit }
      end
    end
  end

  # DELETE /categories/1
  # DELETE /categories/1.json
  def destroy
    @category.destroy
    respond_to do |format|
      format.html { redirect_to new_category_url, notice: 'Category was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_category
    @category = Category.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def category_params
    params.require(:category).permit(:name, :priority)
  end
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/views/categories/_caption_category.html.erb
    <div class="category_caption">

      <% if category.latest_article.present? %>

            <div class="category_img img<%= index %>">
          
                <%= image_tag(category.latest_article.image) %>

            </div>
            <div class="category_content content<%= index %>">
                <p class="category_name">
                    <%= link_to category_path(category) do %>
                        <%= category.name %>
                    <%end%>
                </p>
                <p class="category_hero_title"><%= category.latest_article.title %></p>
                <p class="category_hero_content">
                    <%= truncate(category.latest_article.text, :omission => "...", :length => 300) %>
                </p>

                <%= link_to 'Read more..', article_path(category.latest_article), class: 'category_hero_readmore' %>

            </div>

      <% else %>
            <div class="category_img img<%= index %>">
                <%= image_tag(asset_path("default.jpg")) %>
            </div>
            <div class="category_content content<%= index %>">
              <p class="category_name">
                <%= link_to category_path(category) do %>
                    <%= category.name %>
                <%end%>
              </p>
              <p class="category_hero_title">More articles comming soon in this category ...</p>
            </div>
      <% end %>

    </div>

app/views/categories/_form.html.erb
<section class="article_editor">
  <%= form_with(model: category, local: true) do |form| %>
    <div class="editor_article_content">

        <div class="editor_article_content_wrapper">
          <p class="content_header">List of Existing Categories:</p>

          <table class="category_editor_table_displayer">
              <thead>
                <tr>
                  <th>Category</th>
                  <th>Priority</th>
                  <th>Articles</th>
                  <th>Votes</th>
                  <th>Delete</th>
                  <th>Edit</th>
                </tr>
              </thead>
              <tbody>
                  <% @categories.each do |category| %>
                    <tr>
                      <td>
                        <%= link_to category_path(category) do %>
                          <%= category.name %>
                        <% end %>
                      </td>
                      <td class="numeric"><%= category.priority %></td>
                      <td class="numeric"><%= category.articles_count %></td>
                      <td class="numeric"><%= category.votes_count %></td>
                      <td>
                        <%= link_to category, method: :delete, data: { confirm: 'Are you sure?' } do %>
                                <svg width="1.5em" height="1.5em" viewBox="0 0 16 16" class="bi bi-trash" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
                                  <path d="M5.5 5.5A.5.5 0 0 1 6 6v6a.5.5 0 0 1-1 0V6a.5.5 0 0 1 .5-.5zm2.5 0a.5.5 0 0 1 .5.5v6a.5.5 0 0 1-1 0V6a.5.5 0 0 1 .5-.5zm3 .5a.5.5 0 0 0-1 0v6a.5.5 0 0 0 1 0V6z"/>
                                  <path fill-rule="evenodd" d="M14.5 3a1 1 0 0 1-1 1H13v9a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2V4h-.5a1 1 0 0 1-1-1V2a1 1 0 0 1 1-1H6a1 1 0 0 1 1-1h2a1 1 0 0 1 1 1h3.5a1 1 0 0 1 1 1v1zM4.118 4L4 4.059V13a1 1 0 0 0 1 1h6a1 1 0 0 0 1-1V4.059L11.882 4H4.118zM2.5 3V2h11v1h-11z"/>
                                </svg>
                        <% end %>
                      </td>
                      <td>
                        <%= link_to edit_category_path(category) do %>
                                <svg width="1.5em" height="1.5em" viewBox="0 0 16 16" class="bi bi-tools" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
                                  <path fill-rule="evenodd" d="M0 1l1-1 3.081 2.2a1 1 0 0 1 .419.815v.07a1 1 0 0 0 .293.708L10.5 9.5l.914-.305a1 1 0 0 1 1.023.242l3.356 3.356a1 1 0 0 1 0 1.414l-1.586 1.586a1 1 0 0 1-1.414 0l-3.356-3.356a1 1 0 0 1-.242-1.023L9.5 10.5 3.793 4.793a1 1 0 0 0-.707-.293h-.071a1 1 0 0 1-.814-.419L0 1zm11.354 9.646a.5.5 0 0 0-.708.708l3 3a.5.5 0 0 0 .708-.708l-3-3z"/>
                                  <path fill-rule="evenodd" d="M15.898 2.223a3.003 3.003 0 0 1-3.679 3.674L5.878 12.15a3 3 0 1 1-2.027-2.027l6.252-6.341A3 3 0 0 1 13.778.1l-2.142 2.142L12 4l1.757.364 2.141-2.141zm-13.37 9.019L3.001 11l.471.242.529.026.287.445.445.287.026.529L5 13l-.242.471-.026.529-.445.287-.287.445-.529.026L3 15l-.471-.242L2 14.732l-.287-.445L1.268 14l-.026-.529L1 13l.242-.471.026-.529.445-.287.287-.445.529-.026z"/>
                                </svg>
                        <% end %>
                      </td>
                    </tr>

                  <% end %>
              </tbody>
          </table>
          
        </div>

    </div>
    <div class="editor_article_header">
      <h1><%= form_title %></h1>
    </div>

    <div class="editor_article_toolbox">
      <div class="editor_article_toolbox_container">

        <div class="form_fields">

              <div class="article_editor_field">
                <%= form.label :name %>
                <%= form.text_field :name %>
              </div>

              <div class="article_editor_field">
                  <%= form.label :priority %>
                  <%= form.number_field :priority %>
              </div>

              <div class="article_editor_actions">
                <%= form.submit %>
              </div>
        </div>

      </div>

    </div>
  <% end %>
</section>

app/views/categories/edit.html.erb
<% provide(:title, 'Edit Category')%>

<%= render 'form', category: @category, form_title: 'Editing Category:' %>

app/views/categories/index.html.erb
<% provide(:title, 'Categories')%>

<section class="all_categories">

  <% @categories.each_with_index do |category, index| %>

      <%= render 'categories/caption_category', category: category, index: index %>

  <% end %>

</section>

<section class="pagination_displayer">
  <%= will_paginate @categories %>
</section>

app/views/categories/new.html.erb
<% provide(:title, 'New Category')%>

<%= render 'form', category: @category, form_title: 'Adding New Category:' %>

app/views/categories/show.html.erb
<% provide(:title, @category.name )%>

<section class="category_section">

    <% if @articles.empty? %>

        <div class="category_last_article_wrapper">
          <div class="category_last_article_img">
            <%= image_tag(asset_path('default.jpg')) %>
          </div>
          <div class="category_last_article_content">
            <p class="category_last_article_name">
              <%= link_to categories_path do %>
                  <%= @category.name %>
              <%end%>
              <p class="category_last_article_hero_title">More articles soon in this category ...</p>
            </p>
          </div>
        </div>

    <% else %>

      <% @articles.each_with_index do |article, index| %>

        <%= render 'shared/collection', article: article, index: index, category: @category %>

      <% end %>

    <% end %>

</section>

<section class="pagination_displayer">
  <%= will_paginate @articles %>
</section>